from fastapi import APIRouter, Depends, HTTPException
from sqlmodel import Session, select
from app.database.connection import get_session
from app.models import Exercise
from app.services.llm_service import llm_service
from pydantic import BaseModel
from typing import Optional

router = APIRouter(prefix="/api/llm", tags=["llm"])


class FormRulesResponse(BaseModel):
    exercise_name: str
    form_rules: dict


class StrategyRequest(BaseModel):
    player_a_score: int
    player_b_score: int
    player_b_weakness: Optional[str] = None
    available_exercises: Optional[list[str]] = None


class StrategyResponse(BaseModel):
    exercise_id: str
    rationale: str


class NarrativeRequest(BaseModel):
    winner: str
    loser: str
    winner_score: int
    loser_score: int
    round: int


class NarrativeResponse(BaseModel):
    narrative: str


@router.post("/form-rules/{exercise_name}", response_model=FormRulesResponse)
async def get_form_rules(exercise_name: str):
    """Get form rules for an exercise (generated by LLM)"""
    form_rules = await llm_service.generate_form_rules(exercise_name)
    return FormRulesResponse(
        exercise_name=exercise_name,
        form_rules=form_rules,
    )


@router.post("/strategy", response_model=StrategyResponse)
async def get_strategy(request: StrategyRequest):
    """Get strategy recommendation for next round"""
    strategy = await llm_service.recommend_strategy(
        player_a_score=request.player_a_score,
        player_b_score=request.player_b_score,
        player_b_weakness=request.player_b_weakness,
        available_exercises=request.available_exercises,
    )
    return StrategyResponse(
        exercise_id=strategy.get("exercise_id", "push-ups"),
        rationale=strategy.get("rationale", "Default recommendation"),
    )


@router.post("/narrative", response_model=NarrativeResponse)
async def get_narrative(request: NarrativeRequest):
    """Generate narrative commentary for round result"""
    round_result = {
        "winner": request.winner,
        "loser": request.loser,
        "winner_score": request.winner_score,
        "loser_score": request.loser_score,
        "round": request.round,
    }
    narrative = await llm_service.generate_narrative(round_result)
    return NarrativeResponse(narrative=narrative)

class ChatRequest(BaseModel):
    message: str
    history: Optional[list[dict[str, str]]] = None


class ChatResponse(BaseModel):
    response: str


@router.post("/chat", response_model=ChatResponse)
async def general_chat(request: ChatRequest):
    """General fitness chat assistant endpoint"""
    response = await llm_service.general_chat(request.message, request.history)
    return ChatResponse(response=response)

class WorkoutPlanRequest(BaseModel):
    user_goal: str
    fitness_level: str


@router.post("/workout-plan")
async def generate_workout_plan(request: WorkoutPlanRequest):
    """Personalized workout plan endpoint"""
    plan = await llm_service.generate_workout_plan(request.user_goal, request.fitness_level)
    return plan
