import { useState } from 'react';
import { Card, CardContent, CardHeader, CardTitle } from '../ui/card';
import { Button } from '../ui/button';
import { Sparkles, Dumbbell, Target, ChevronRight } from 'lucide-react';
import api from '../../services/api';

export function RecommendationScreen() {
  const [goal, setGoal] = useState('strength');
  const [level, setLevel] = useState('intermediate');
  const [loading, setLoading] = useState(false);
  const [plan, setPlan] = useState<any>(null);

  const generatePlan = async () => {
    setLoading(true);
    try {
      const response = await api.post('/api/llm/workout-plan', {
        user_goal: goal,
        fitness_level: level
      });
      setPlan(response.data);
    } catch (error) {
      console.error('Failed to generate plan:', error);
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="p-6 space-y-6 max-w-4xl mx-auto pb-24">
      <h1 className="text-3xl audiowide-regular text-cyan-400 mb-2 flex items-center">
        <Sparkles className="mr-3 h-8 w-8" /> AI RECOMMENDATIONS
      </h1>
      <p className="text-neutral-400 mb-8">Personalized workout routines generated by ForgeBot AI.</p>

      {!plan ? (
        <Card className="bg-black/40 border-white/10 backdrop-blur-md">
          <CardHeader>
            <CardTitle className="text-lg">Set Your Parameters</CardTitle>
          </CardHeader>
          <CardContent className="space-y-6">
            <div className="space-y-3">
              <label className="text-xs uppercase tracking-widest text-neutral-500">Your Main Goal</label>
              <div className="flex flex-wrap gap-2">
                {['Strength', 'Endurance', 'Fat Loss', 'Muscle Gain'].map(g => (
                  <Button 
                    key={g} 
                    variant={goal === g.toLowerCase() ? 'default' : 'outline'}
                    onClick={() => setGoal(g.toLowerCase())}
                    className={goal === g.toLowerCase() ? 'bg-cyan-600 text-black' : 'border-neutral-800'}
                  >
                    {g}
                  </Button>
                ))}
              </div>
            </div>

            <div className="space-y-3">
              <label className="text-xs uppercase tracking-widest text-neutral-500">Fitness Level</label>
              <div className="flex flex-wrap gap-2">
                {['Beginner', 'Intermediate', 'Advanced', 'Athlete'].map(l => (
                  <Button 
                    key={l}
                    variant={level === l.toLowerCase() ? 'default' : 'outline'}
                    onClick={() => setLevel(l.toLowerCase())}
                    className={level === l.toLowerCase() ? 'bg-cyan-600 text-black' : 'border-neutral-800'}
                  >
                    {l}
                  </Button>
                ))}
              </div>
            </div>

            <Button 
              onClick={generatePlan}
              disabled={loading}
              className="w-full h-12 bg-gradient-to-r from-cyan-600 to-blue-600 hover:from-cyan-500 hover:to-blue-500 text-black font-bold uppercase"
            >
              {loading ? 'Consulting ForgeBot...' : 'Generate My Workspace Plan'}
            </Button>
          </CardContent>
        </Card>
      ) : (
        <div className="space-y-6 animate-in fade-in slide-in-from-bottom-8 duration-500">
          <Card className="bg-black/60 border-cyan-500/30 backdrop-blur-xl">
            <CardHeader className="flex flex-row items-center justify-between border-b border-white/5 pb-4">
              <div>
                <CardTitle className="text-2xl text-cyan-400">{plan.plan_name}</CardTitle>
                <p className="text-xs text-neutral-500 mt-1 uppercase tracking-widest">Tailored for {level} • Goal: {goal}</p>
              </div>
              <Button variant="outline" onClick={() => setPlan(null)} className="text-xs text-neutral-400">Restart</Button>
            </CardHeader>
            <CardContent className="pt-6">
              <div className="space-y-4">
                {plan.exercises.map((ex: any, i: number) => (
                  <div key={i} className="flex items-center p-4 bg-white/5 rounded-xl border border-white/5 hover:border-cyan-500/30 transition-colors">
                    <div className="w-10 h-10 rounded-full bg-cyan-600/20 flex items-center justify-center text-cyan-400 mr-4 font-bold">
                      {i + 1}
                    </div>
                    <div className="flex-1">
                      <h4 className="font-semibold text-white">{ex.name}</h4>
                      <p className="text-sm text-neutral-400">{ex.reps_or_duration || ex.reps}</p>
                    </div>
                    {ex.sets && <div className="text-xs font-mono text-cyan-500">{ex.sets} SETS</div>}
                    <ChevronRight className="ml-4 h-4 w-4 text-neutral-700" />
                  </div>
                ))}
              </div>

              <div className="mt-8 p-4 bg-cyan-500/10 rounded-xl border border-cyan-500/20 flex items-start">
                <Target className="h-5 w-5 text-cyan-400 mr-3 mt-0.5 flex-shrink-0" />
                <div>
                  <p className="text-xs font-bold text-cyan-400 uppercase tracking-widest mb-1">ForgeBot Tip</p>
                  <p className="text-sm text-neutral-200">{plan.coach_tip}</p>
                </div>
              </div>
              
              <Button className="w-full mt-6 bg-white text-black hover:bg-neutral-200 flex items-center justify-center">
                <Dumbbell className="mr-2 h-4 w-4" /> Start This Workout
              </Button>
            </CardContent>
          </Card>
        </div>
      )}
    </div>
  );
}
